# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"b\n\x0f\x43urrencyMessage\x12-\n\x0c\x63urrencyEnum\x18\x01 \x01(\x0e\x32\x17.streaming.CurrencyEnum\x12\x12\n\nvalueInPLN\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"L\n\x0bUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12-\n\x0c\x63urrencyEnum\x18\x02 \x01(\x0e\x32\x17.streaming.CurrencyEnum* \n\x0c\x43urrencyEnum\x12\x07\n\x03\x44OL\x10\x00\x12\x07\n\x03\x45UR\x10\x01\x32R\n\x0f\x43urrencyService\x12?\n\x07\x43onnect\x12\x16.streaming.UserRequest\x1a\x1a.streaming.CurrencyMessage0\x01\x42\x1f\n\x0borg.exampleB\x0eStreamingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013org.exampleB\016StreamingProtoP\001'
  _globals['_CURRENCYENUM']._serialized_start=208
  _globals['_CURRENCYENUM']._serialized_end=240
  _globals['_CURRENCYMESSAGE']._serialized_start=30
  _globals['_CURRENCYMESSAGE']._serialized_end=128
  _globals['_USERREQUEST']._serialized_start=130
  _globals['_USERREQUEST']._serialized_end=206
  _globals['_CURRENCYSERVICE']._serialized_start=242
  _globals['_CURRENCYSERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
