// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: subscription_options.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsRequest) Reset() {
	*x = ListOptionsRequest{}
	mi := &file_subscription_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsRequest) ProtoMessage() {}

func (x *ListOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsRequest.ProtoReflect.Descriptor instead.
func (*ListOptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_options_proto_rawDescGZIP(), []int{0}
}

type ListOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetName     []AssetName            `protobuf:"varint,1,rep,packed,name=asset_name,json=assetName,proto3,enum=pb.AssetName" json:"asset_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOptionsResponse) Reset() {
	*x = ListOptionsResponse{}
	mi := &file_subscription_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOptionsResponse) ProtoMessage() {}

func (x *ListOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOptionsResponse.ProtoReflect.Descriptor instead.
func (*ListOptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_options_proto_rawDescGZIP(), []int{1}
}

func (x *ListOptionsResponse) GetAssetName() []AssetName {
	if x != nil {
		return x.AssetName
	}
	return nil
}

type RemoveSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetName     AssetName              `protobuf:"varint,1,opt,name=asset_name,json=assetName,proto3,enum=pb.AssetName" json:"asset_name,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionRequest) Reset() {
	*x = RemoveSubscriptionRequest{}
	mi := &file_subscription_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionRequest) ProtoMessage() {}

func (x *RemoveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_options_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSubscriptionRequest) GetAssetName() AssetName {
	if x != nil {
		return x.AssetName
	}
	return AssetName_UNKNOWN
}

func (x *RemoveSubscriptionRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type RemoveSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionResponse) Reset() {
	*x = RemoveSubscriptionResponse{}
	mi := &file_subscription_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionResponse) ProtoMessage() {}

func (x *RemoveSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_options_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveSubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_subscription_options_proto protoreflect.FileDescriptor

const file_subscription_options_proto_rawDesc = "" +
	"\n" +
	"\x1asubscription_options.proto\x12\x02pb\x1a\x1asubscription_message.proto\"\x14\n" +
	"\x12ListOptionsRequest\"C\n" +
	"\x13ListOptionsResponse\x12,\n" +
	"\n" +
	"asset_name\x18\x01 \x03(\x0e2\r.pb.AssetNameR\tassetName\"g\n" +
	"\x19RemoveSubscriptionRequest\x12,\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\x0e2\r.pb.AssetNameR\tassetName\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\"6\n" +
	"\x1aRemoveSubscriptionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\x1b\n" +
	"\tsubber.pbP\x01Z\fsubber-go/pbb\x06proto3"

var (
	file_subscription_options_proto_rawDescOnce sync.Once
	file_subscription_options_proto_rawDescData []byte
)

func file_subscription_options_proto_rawDescGZIP() []byte {
	file_subscription_options_proto_rawDescOnce.Do(func() {
		file_subscription_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_options_proto_rawDesc), len(file_subscription_options_proto_rawDesc)))
	})
	return file_subscription_options_proto_rawDescData
}

var file_subscription_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_subscription_options_proto_goTypes = []any{
	(*ListOptionsRequest)(nil),         // 0: pb.ListOptionsRequest
	(*ListOptionsResponse)(nil),        // 1: pb.ListOptionsResponse
	(*RemoveSubscriptionRequest)(nil),  // 2: pb.RemoveSubscriptionRequest
	(*RemoveSubscriptionResponse)(nil), // 3: pb.RemoveSubscriptionResponse
	(AssetName)(0),                     // 4: pb.AssetName
}
var file_subscription_options_proto_depIdxs = []int32{
	4, // 0: pb.ListOptionsResponse.asset_name:type_name -> pb.AssetName
	4, // 1: pb.RemoveSubscriptionRequest.asset_name:type_name -> pb.AssetName
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_subscription_options_proto_init() }
func file_subscription_options_proto_init() {
	if File_subscription_options_proto != nil {
		return
	}
	file_subscription_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_options_proto_rawDesc), len(file_subscription_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_options_proto_goTypes,
		DependencyIndexes: file_subscription_options_proto_depIdxs,
		MessageInfos:      file_subscription_options_proto_msgTypes,
	}.Build()
	File_subscription_options_proto = out.File
	file_subscription_options_proto_goTypes = nil
	file_subscription_options_proto_depIdxs = nil
}
