// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: subscription_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_subscription_service_proto protoreflect.FileDescriptor

const file_subscription_service_proto_rawDesc = "" +
	"\n" +
	"\x1asubscription_service.proto\x12\x02pb\x1a\x1asubscription_message.proto\x1a\x1asubscription_options.proto2\x91\x01\n" +
	"\x06Subber\x12E\n" +
	"\fSubscription\x12\x17.pb.SubscriptionRequest\x1a\x18.pb.SubscriptionResponse\"\x000\x01\x12@\n" +
	"\vListOptions\x12\x16.pb.ListOptionsRequest\x1a\x17.pb.ListOptionsResponse\"\x00B\x1b\n" +
	"\tsubber.pbP\x01Z\fsubber-go/pbb\x06proto3"

var file_subscription_service_proto_goTypes = []any{
	(*SubscriptionRequest)(nil),  // 0: pb.SubscriptionRequest
	(*ListOptionsRequest)(nil),   // 1: pb.ListOptionsRequest
	(*SubscriptionResponse)(nil), // 2: pb.SubscriptionResponse
	(*ListOptionsResponse)(nil),  // 3: pb.ListOptionsResponse
}
var file_subscription_service_proto_depIdxs = []int32{
	0, // 0: pb.Subber.Subscription:input_type -> pb.SubscriptionRequest
	1, // 1: pb.Subber.ListOptions:input_type -> pb.ListOptionsRequest
	2, // 2: pb.Subber.Subscription:output_type -> pb.SubscriptionResponse
	3, // 3: pb.Subber.ListOptions:output_type -> pb.ListOptionsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscription_service_proto_init() }
func file_subscription_service_proto_init() {
	if File_subscription_service_proto != nil {
		return
	}
	file_subscription_message_proto_init()
	file_subscription_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_service_proto_rawDesc), len(file_subscription_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_service_proto_goTypes,
		DependencyIndexes: file_subscription_service_proto_depIdxs,
	}.Build()
	File_subscription_service_proto = out.File
	file_subscription_service_proto_goTypes = nil
	file_subscription_service_proto_depIdxs = nil
}
