// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: subscription_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetName int32

const (
	AssetName_UNKNOWN   AssetName = 0
	AssetName_GOLD      AssetName = 1
	AssetName_SILVER    AssetName = 2
	AssetName_BITCOIN   AssetName = 3
	AssetName_CRUDE_OIL AssetName = 4
)

// Enum value maps for AssetName.
var (
	AssetName_name = map[int32]string{
		0: "UNKNOWN",
		1: "GOLD",
		2: "SILVER",
		3: "BITCOIN",
		4: "CRUDE_OIL",
	}
	AssetName_value = map[string]int32{
		"UNKNOWN":   0,
		"GOLD":      1,
		"SILVER":    2,
		"BITCOIN":   3,
		"CRUDE_OIL": 4,
	}
)

func (x AssetName) Enum() *AssetName {
	p := new(AssetName)
	*p = x
	return p
}

func (x AssetName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetName) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_message_proto_enumTypes[0].Descriptor()
}

func (AssetName) Type() protoreflect.EnumType {
	return &file_subscription_message_proto_enumTypes[0]
}

func (x AssetName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetName.Descriptor instead.
func (AssetName) EnumDescriptor() ([]byte, []int) {
	return file_subscription_message_proto_rawDescGZIP(), []int{0}
}

type SubscriptionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AssetName AssetName              `protobuf:"varint,1,opt,name=asset_name,json=assetName,proto3,enum=pb.AssetName" json:"asset_name,omitempty"`
	Threshold float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	// Types that are valid to be assigned to Condition:
	//
	//	*SubscriptionRequest_GreaterThan
	//	*SubscriptionRequest_LessThan
	Condition     isSubscriptionRequest_Condition `protobuf_oneof:"Condition"`
	ClientUUID    string                          `protobuf:"bytes,5,opt,name=clientUUID,proto3" json:"clientUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_subscription_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_message_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionRequest) GetAssetName() AssetName {
	if x != nil {
		return x.AssetName
	}
	return AssetName_UNKNOWN
}

func (x *SubscriptionRequest) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SubscriptionRequest) GetCondition() isSubscriptionRequest_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *SubscriptionRequest) GetGreaterThan() bool {
	if x != nil {
		if x, ok := x.Condition.(*SubscriptionRequest_GreaterThan); ok {
			return x.GreaterThan
		}
	}
	return false
}

func (x *SubscriptionRequest) GetLessThan() bool {
	if x != nil {
		if x, ok := x.Condition.(*SubscriptionRequest_LessThan); ok {
			return x.LessThan
		}
	}
	return false
}

func (x *SubscriptionRequest) GetClientUUID() string {
	if x != nil {
		return x.ClientUUID
	}
	return ""
}

type isSubscriptionRequest_Condition interface {
	isSubscriptionRequest_Condition()
}

type SubscriptionRequest_GreaterThan struct {
	GreaterThan bool `protobuf:"varint,3,opt,name=GreaterThan,proto3,oneof"`
}

type SubscriptionRequest_LessThan struct {
	LessThan bool `protobuf:"varint,4,opt,name=LessThan,proto3,oneof"`
}

func (*SubscriptionRequest_GreaterThan) isSubscriptionRequest_Condition() {}

func (*SubscriptionRequest_LessThan) isSubscriptionRequest_Condition() {}

type SubscriptionResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	AssetName       AssetName                `protobuf:"varint,1,opt,name=asset_name,json=assetName,proto3,enum=pb.AssetName" json:"asset_name,omitempty"`
	CurrentPrice    float64                  `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Message         string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CurrentTime     *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	LastTimeOccured []*timestamppb.Timestamp `protobuf:"bytes,5,rep,name=last_time_occured,json=lastTimeOccured,proto3" json:"last_time_occured,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	mi := &file_subscription_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_message_proto_rawDescGZIP(), []int{1}
}

func (x *SubscriptionResponse) GetAssetName() AssetName {
	if x != nil {
		return x.AssetName
	}
	return AssetName_UNKNOWN
}

func (x *SubscriptionResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *SubscriptionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubscriptionResponse) GetCurrentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentTime
	}
	return nil
}

func (x *SubscriptionResponse) GetLastTimeOccured() []*timestamppb.Timestamp {
	if x != nil {
		return x.LastTimeOccured
	}
	return nil
}

var File_subscription_message_proto protoreflect.FileDescriptor

const file_subscription_message_proto_rawDesc = "" +
	"\n" +
	"\x1asubscription_message.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n" +
	"\x13SubscriptionRequest\x12,\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\x0e2\r.pb.AssetNameR\tassetName\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12\"\n" +
	"\vGreaterThan\x18\x03 \x01(\bH\x00R\vGreaterThan\x12\x1c\n" +
	"\bLessThan\x18\x04 \x01(\bH\x00R\bLessThan\x12\x1e\n" +
	"\n" +
	"clientUUID\x18\x05 \x01(\tR\n" +
	"clientUUIDB\v\n" +
	"\tCondition\"\x8a\x02\n" +
	"\x14SubscriptionResponse\x12,\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\x0e2\r.pb.AssetNameR\tassetName\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\x01R\fcurrentPrice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\fcurrent_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcurrentTime\x12F\n" +
	"\x11last_time_occured\x18\x05 \x03(\v2\x1a.google.protobuf.TimestampR\x0flastTimeOccured*J\n" +
	"\tAssetName\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04GOLD\x10\x01\x12\n" +
	"\n" +
	"\x06SILVER\x10\x02\x12\v\n" +
	"\aBITCOIN\x10\x03\x12\r\n" +
	"\tCRUDE_OIL\x10\x04B\x1b\n" +
	"\tsubber.pbP\x01Z\fsubber-go/pbb\x06proto3"

var (
	file_subscription_message_proto_rawDescOnce sync.Once
	file_subscription_message_proto_rawDescData []byte
)

func file_subscription_message_proto_rawDescGZIP() []byte {
	file_subscription_message_proto_rawDescOnce.Do(func() {
		file_subscription_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_message_proto_rawDesc), len(file_subscription_message_proto_rawDesc)))
	})
	return file_subscription_message_proto_rawDescData
}

var file_subscription_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_subscription_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscription_message_proto_goTypes = []any{
	(AssetName)(0),                // 0: pb.AssetName
	(*SubscriptionRequest)(nil),   // 1: pb.SubscriptionRequest
	(*SubscriptionResponse)(nil),  // 2: pb.SubscriptionResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_subscription_message_proto_depIdxs = []int32{
	0, // 0: pb.SubscriptionRequest.asset_name:type_name -> pb.AssetName
	0, // 1: pb.SubscriptionResponse.asset_name:type_name -> pb.AssetName
	3, // 2: pb.SubscriptionResponse.current_time:type_name -> google.protobuf.Timestamp
	3, // 3: pb.SubscriptionResponse.last_time_occured:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_subscription_message_proto_init() }
func file_subscription_message_proto_init() {
	if File_subscription_message_proto != nil {
		return
	}
	file_subscription_message_proto_msgTypes[0].OneofWrappers = []any{
		(*SubscriptionRequest_GreaterThan)(nil),
		(*SubscriptionRequest_LessThan)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_message_proto_rawDesc), len(file_subscription_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_message_proto_goTypes,
		DependencyIndexes: file_subscription_message_proto_depIdxs,
		EnumInfos:         file_subscription_message_proto_enumTypes,
		MessageInfos:      file_subscription_message_proto_msgTypes,
	}.Build()
	File_subscription_message_proto = out.File
	file_subscription_message_proto_goTypes = nil
	file_subscription_message_proto_depIdxs = nil
}
