// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.1
// source: subscription_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subber_Subscription_FullMethodName = "/pb.Subber/Subscription"
)

// SubberClient is the client API for Subber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubberClient interface {
	Subscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionResponse], error)
}

type subberClient struct {
	cc grpc.ClientConnInterface
}

func NewSubberClient(cc grpc.ClientConnInterface) SubberClient {
	return &subberClient{cc}
}

func (c *subberClient) Subscription(ctx context.Context, in *SubscriptionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscriptionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Subber_ServiceDesc.Streams[0], Subber_Subscription_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscriptionRequest, SubscriptionResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Subber_SubscriptionClient = grpc.ServerStreamingClient[SubscriptionResponse]

// SubberServer is the server API for Subber service.
// All implementations must embed UnimplementedSubberServer
// for forward compatibility.
type SubberServer interface {
	Subscription(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionResponse]) error
	mustEmbedUnimplementedSubberServer()
}

// UnimplementedSubberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubberServer struct{}

func (UnimplementedSubberServer) Subscription(*SubscriptionRequest, grpc.ServerStreamingServer[SubscriptionResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}
func (UnimplementedSubberServer) mustEmbedUnimplementedSubberServer() {}
func (UnimplementedSubberServer) testEmbeddedByValue()                {}

// UnsafeSubberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubberServer will
// result in compilation errors.
type UnsafeSubberServer interface {
	mustEmbedUnimplementedSubberServer()
}

func RegisterSubberServer(s grpc.ServiceRegistrar, srv SubberServer) {
	// If the following call pancis, it indicates UnimplementedSubberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subber_ServiceDesc, srv)
}

func _Subber_Subscription_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscriptionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubberServer).Subscription(m, &grpc.GenericServerStream[SubscriptionRequest, SubscriptionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Subber_SubscriptionServer = grpc.ServerStreamingServer[SubscriptionResponse]

// Subber_ServiceDesc is the grpc.ServiceDesc for Subber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Subber",
	HandlerType: (*SubberServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscription",
			Handler:       _Subber_Subscription_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "subscription_service.proto",
}
